apiVersion: apps/v1
kind: Deployment
metadata:
  name: springproject-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springproject
  template:
    metadata:
      labels:
        app: springproject
    spec:
      containers:
      - name: springproject
        image: firashachicha/springproject:latest
        ports:
        - containerPort: 8080
