version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: db            # Use 'db' as the database name, as configured in your application.properties
    ports:
      - "3306:3306"
    volumes:
      - sql_db:/var/lib/mysql   # Persistent volume for MySQL data

  backend:
    image: mohamedzrig27/kaddem:latest  # Replace with your built Spring Boot Docker image
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8089:8089"                 # Matches the server.port in application.properties
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/kaddem\db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /kaddem
    volumes:
      - spring_logs:/app/logs      # Optional volume for backend logs

volumes:
  sql_db:
  spring_logs: