version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: db
    volumes:
      - mysql-db:/var/lib/mysql

  spring-boot-app:
    image: medzrig/kaddem:latest
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - springApp:/app/logs

volumes:
  mysql-db:
  springApp:
